# Working with Data 

<div class="alert alert-block alert-info">
<h2>Overview</h2>

Questions:

* How do I work with numerical data presented in tables?
* What is NumPy? What is pandas?
* What is an array? What is a dataframe?

Objectives:

* Use functions in `numpy` to read in tabular data.
* Take 2D slices of data in numpy arrays.
* Use 2D slices to work with particular rows or columns of data.
* Use the `range()` function in `for` loops.
* Use `numpy` functions to analyze data.
* Use `pandas` dataframes for more complex data.

</div>

Most scientists work with a lot of numerical data. In this module we will focus on reading in and analyzing numerical data, visualizing the data, and working with arrays.

## Reading in Tabular Data

In our last module, we used the `readlines()` function to read in a complex output file. In theory, you could always use the `readlines()` function, and then use the data parsing tools we learned in the previous module to format the data as you needed. But sometimes there are other ways that make more sense, particularly if the data is (1) all or mostly one type of data (for example, all numbers) and/or (2) formatted in a table. Frequently, a table will be mostly numbers, but have column or row labels.

A common table format is the CSV file or comma separated values. This is exactly what it sounds like. Data is presented in rows, with each value separated by a comma. If you have data in a spreadsheet program that you need to import into a python code, you can save the data as a .csv file to read it in.

In this example, we have a CSV file that contains data from a molecular dynamics trajectory. We have a 20 ns simulation that used a 2 fs timestep. The data was saved to the trajectory file every 1000 steps, so our file has 10,000 timesteps. At each timestep, we are interested in the distance between particular atoms. These trajectories were generated with the AMBER molecular dynamics program and the distances were measured with the python program MDAnalysis. The table of atomic distances was saved as a CVS file called “distance_data_headers.csv”. This file is included in the data folder. Open the file on ChemCompute to determine its structure.

In analyzing tabular data, we often need to perform the same types of calculations (averaging, calculating the minimum or maximum of the data set), so we are going to use a python library, in this case, one that contains lots of functions to perform math operations. This library is called `numpy`. The `numpy` library has several functions available to read in tabular data. One of these functions is the `genfromtxt()` function. We will use the `help()` function to learn more about `genfromtxt()` and how it works. The help function can be used for nearly any built in python function and many libraries. When `numpy` is imported, it is often shortened to `np` as shown below:

In [18]:
import numpy as np      #commonly shortened name for library
help(np.genfromtxt) 

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

The help menu shows us all the options we can use with this function. The first input `fname` is the filename we are reading in. We must put a values for this option because it does not have a default value. All the other options have a default value that is shown after the = sign. We only need to specify these options if we don’t want to use the default value. For example, in our file, all the values were not numbers so we don’t want to use the datatype `float`, we want to use something else. If you have mixed datatypes, like we do here, we want to use `'unicode'`. In our file, our values are separated by commas; we indicate that with `delimiter=','`.

<div class="alert alert-block alert-success"> 
<strong>Should you skip the headers?</strong>

If you read the help information carefully, you may notice the `skip_header` option, where you can specify a number of lines to skip at the beginning of the file. If we did this, then our values would all be numbers and we could use dtype=’float’, which is the default. In this example, we are not going to do that because we might want to use the headers later to label things, but keep this option in mind because you might want to use it in a later project.

</div>  

Now we have have our plan, we are ready to import our data with `genfromtxt()`.

First, we have to get the path to our file. Remember from previous lessons that we use the `os.path` module to do this.

In [19]:
import os

distance_file = os.path.join('data', 'distance_data_headers.csv')

distances = np.genfromtxt(distance_file, delimiter=',', dtype='unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


The output of this function is a list of lists; that is, each row is a entry in our list, but each row is itself a list of values. We can see that the first row is our column headings and all the other rows contain numerical data.

If we were to read this in with the readlines() function, we would have to split each line of the file, use the `append` function to make a new list for each row, and THEN put all those lists together into a list of lists. Using the appropriate `numpy` function makes our life much easier.

## Manipulating Tabular Data

Now we can clearly see that our first line of data is headings for our columns, and will need to be stored as strings, whereas all the rest of the data is numerical and will need to be stored as floats. Let’s take a slice of the data that is just the headers.

In [4]:
headers = distances[0]
print(headers)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


Now take a slice of the data that contains all the numerical values. Replace the '0' with the appropriate range.

In [6]:
data = distances[0]
print(data)

[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


Even though we now have a list of lists that is just the numbers, the numbers are all still strings. We know this because (1) we read them all in as unicode and (2) if we look at the output of the print statement, we can see that each number is enclosed in single quotes, indicating that it is a string. We need to recast these values as floats. The `numpy` library has a built-in function to accomplish this. In this case, keeping a variable with all the same information as strings is not useful to us, so this is a case where we are going to overwrite our variable data.

In [8]:
data = data.astype(float)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


We already learned how to address a particular element of a list and how to take a slice of a list to create a new list. Now that we have an array, we now need two indices to address a particular element of the array. The notation to address an element of the array is always

```python
 array_name[row,column]

```

Before running the following cells, predict the outcome.

In [9]:
print(data[0,1])
print(data[1,0])

8.9542
2.0


You can also take two-dimensional slices of an array where you specify a range of rows and a range of columns for the slice. For example, sometimes it is easier to work with a small subset of our data for testing rather than the full data set. This command takes a slice that includes only the first ten rows and the first three columns of our data.

In [10]:
small_data = data[0:10,0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


Remember that counting starts at zero, so 0:10 means start at row zero and include all rows, up to but not including 10. Just as with the one-dimensional list slices, if you don’t include a number before the `:` the slice automatically starts with `list_name[0]`. If you don’t include a number after the `:` the slice goes to the end of the list. Therefore, if you don’t include either, a `:` means *every row* or *every column

Before running the following cells, predict the outcome.

In [13]:
print(small_data[5,:])
print(small_data[:,1:])

[6.     9.0462 6.2553]
[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


** Analyzing Tabular Data

The `numpy` library has numerous built-in functions. For example, to calculate the average (mean) of a data set, the syntax is
```python
data_average = numpy.mean(data_set)
```

Let’s say we want to calculate the average distance for a particular measurement over the whole simulation. We want to calculate the average of one of the columns. We can take a slice of our data array that is just one column. Then we can find the average of that column. It doesn’t make sense to average the frame numbers, so let’s do the THR4_ATP column first.

In [23]:
thr4_atp = data[:,1]  # Every row, just the THR4_ATP column
avg_thr4_atp = np.mean(thr4_atp)
print(avg_thr4_atp)


10.876950930000001


This is correct, but now we would like to calculate the average of every column. This seems like a job for a `for` loop, but unlike last time, we don’t want to count over a particular list and do something for every item, we want to do something a particular number of times. Basically, we want to take that `1` and let it be every number, up to the number of columns. This is a task for the `range()` function. The general syntax is
```python
range(start, end)

```
and we can use `range()` in a `for` loop.

In our example, the “end” value needs to be the number of columns of data.

<div class="alert alert-block alert-warning"> 
<strong>Check your understanding</strong>
    
Complete the code below to determine the number of columns in our data set using the `len` function. Save this value as a variable called num_columns.

</div>

In [15]:
num_columns = 
print(num_columns)

5


Now that we know the number of columns, we can use the `range()` function to set up our `for` loop.

In [16]:
for i in range(1,num_columns):
    column = data[:,i]
    avg_col = np.mean(column)
    print(F'{headers[i]} : {avg_col}')

THR4_ATP : 10.876950930000001
THR4_ASP : 7.342344959999999
TYR6_ATP : 11.209791329999998
TYR6_ASP : 10.9934435


## NumPy Arrays vs. Python Lists

When using `numpy` to import your data a special data type called a numpy array is created. This is similar to the built in list functions in python that were used in the previous activities, but numpy arrays take up less space, are faster, and have more mathematical operations associated with them. All elements in a numpy array must be the same type.

There are also differences in how lists and numpy arrays behave. Let’s look at some of these. We will start with reading in some data from an xyz file. The following block will read a file called water.xyz and saving two numpy arrays - one called coordinates with the molecular `coordinates`, and another called `symbols` with the element symbols.

In [25]:
file_location = os.path.join('data', 'water.xyz')
xyz_file = np.genfromtxt(file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:,0]
coordinates = (xyz_file[:,1:])
coordinates = coordinates.astype(float)

print(symbols)
print(coordinates)


['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


<div class="alert alert-block alert-warning"> 
<strong>Check your understanding</strong>
    
Slice the `coordinates` array to create a new array called `oxygen_coord` which has the x, y, and z coordinate for the oxygen atom.

</div>

Now that we have the oxygen coordinate, let’s imagine we wanted to do something to it. Let’s imagine that we wanted to translate the position of the oxygen atom. We want to translate it 0.1 units in the x direction and -0.1 units in the y direction.

If we were writing for loops like we did before, we might do this by defining a translation vector and using a for loop.

In [28]:
translation_vector = [0.1, -0.1, 0]

oxygen_coord_new = []

for dim in range(3):
    new_position = oxygen_coord[dim] + translation_vector[dim]
    oxygen_coord_new.append(new_position)

print(oxygen_coord_new)


[0.1, -0.107156, 0.965491]


However, since `oxygen_coord` is a numpy array, we could have done this differently. One way numpy arrays and lists are different is that you can easily perform element-wise operations on numpy arrays without loops. You can make your code much faster if you use numpy element-by-element operations instead of loops.

Numpy is smart. If two arrays (or a list and an array), it will guess that you want to do element-wise addition. In the `for` loop we just wrote, we actually wanted an answer that looked like `[x1+x2, y1+y2, z1+z2]` where [x1, x2, x3] was `oxygen_coord` and [y1, y2, y3] was `translation_vector`. Using the power of numpy arrays, we could have instead written

In [29]:
oxygen_coord_new = oxygen_coord + translation_vector
print(oxygen_coord_new)


[ 0.1      -0.107156  0.965491]


Numpy was smart - it looked at the shape of both of these variables, saw they were the same shape, and assumed we wanted to do element-wise operation. You could have also subtracted, multiplied, or divided these, and it would have performed element-wise operations.

Note, that this only worked because `oxygen_coord` was a `numpy` array.

In [30]:
type(oxygen_coord)

numpy.ndarray

What happens if we try this with a list?

In [31]:
oxygen_list = list(oxygen_coord)
type(oxygen_list)


list

In [32]:
oxygen_list + translation_vector

[0.0, -0.007156, 0.965491, 0.1, -0.1, 0]

This process is called concatenation, where the two lists are just joined together. As a note, if you wanted to concatenate the two where `oxygen_coordinate` was a numpy array, you could have done so with the `np.concatenate` function.

You can add two numpy arrays together, multiply arrays by scalars, or do element-wise multiplcation of arrays.

For example, you can multiply two numpy arrays to get their element-wise product. This means that given two vectors `a = np.array([a0, a1, a2])` and `b = np.array([b0, b1, b2])`, `a * b = [a0*b0, a1*a1, a2*b2]`.

In contrast, if `a`and `b` were lists, you would get an error.

To check yourself, before running the follow cells, predict the outcome.

In [33]:
a1 = np.array([2, 1, 0])
a2 = np.array([1, 3, 5])

print(a1 * a2)
print(a1 + a2)

[2 3 0]
[3 4 5]


In [34]:
a1 = [2, 1, 0]
a2 = [1, 3, 5]

print(a1 + a2)
print(a1 * a2)

[2, 1, 0, 1, 3, 5]


TypeError: can't multiply sequence by non-int of type 'list'

## Broadcasting

Another special thing about numpy is something called **broadcasting**. Broadcasting occurs when you attempt mathematical operations on arrays that have different shapes. If possible, the smaller array is “broadcast” across the larger array.

Let’s think about what would happen if we wanted to move every atom in our water molecule by our translation vector.

If you were working with Python lists, or you didn’t know about the features of numpy arrays, you might try to do this with a `for` loop.

In [35]:
new_coordinates = []

for atom in coordinates:
    new_x = atom[0] + translation_vector[0]
    new_y = atom[1] + translation_vector[1]
    new_z = atom[2] + translation_vector[2]
    
    new_coordinates.append([new_x, new_y, new_z])
    
print(new_coordinates)


[[0.1, -0.107156, 0.965491], [0.1, -0.098514, -0.003471], [0.1, 0.831026, 1.207929]]


Broadcasting in `numpy` allows us to achieve that with one command, rather than a `for` loop.

In [36]:
new_coordinates = coordinates + translation_vector

print(new_coordinates)

[[ 0.1      -0.107156  0.965491]
 [ 0.1      -0.098514 -0.003471]
 [ 0.1       0.831026  1.207929]]


For this to work, we have to have two arrays that have a matching dimension. You can see the shape of an array using the function `np.shape`.

In [38]:
np.shape(coordinates)

(3, 3)

In [39]:
np.shape(translation_vector)

(3,)

When you typed, `coordinates + translation_vector`, numpy looked at the shapes of both arrays to figure out if they were compatible.

It starts with the dimensions to the right, so when it saw to matching 3’s it assumed you wanted to do element-wise operation this way, and stretched or ‘broadcast’ the smaller array to match the larger one.

## Logical comparisons

We can also do logical comparisons on whole arrays. For example, to find out if values in the array are greater than 0, we can write the following print statement, which will print either `True` or `False` for each array elelement depending on whehter it is greater than 0 or not.

In [40]:
print(coordinates > 0)

[[False False  True]
 [False  True False]
 [False  True  True]]


To get every value in the array that is greater than 0, we can use this as a list of indices we want, or a slice.

In [41]:
greater_than_0_values = coordinates[coordinates>0]
print(greater_than_0_values)

[0.965491 0.001486 0.931026 1.207929]


## Array Axes

Imagine we wanted to calculate the geometric center of our molecule. To do this, we would need to get the average x coordinate, the average y coordinate, and the average z coordinate.

A `numpy` array can be thought of like a coordinates system. Axis 0 runs along the ROWS, while axis 1 runs along the COLUMNS.

In [45]:
coordinates

array([[ 0.      , -0.007156,  0.965491],
       [-0.      ,  0.001486, -0.003471],
       [ 0.      ,  0.931026,  1.207929]])

In [43]:
center = np.mean(coordinates, axis=0) # mean of each column
print(center)


[0.         0.308452   0.72331633]


In [44]:
center = np.mean(coordinates, axis=1) # mean of each row 
print(center)


[ 3.19445000e-01 -6.61666667e-04  7.12985000e-01]


<div class="alert alert-block alert-success"> 
<strong>Key Points</strong>


* NumPy arrays which are the same size use element-wise operations when added or subtracted
* NumPy uses something called broadcasting for arrays which are not the same size to allow arrays to be added or multiplied.
* NumPy has extensive documentation online - you should check this out if you need to do a computation.


</div>  


## What is pandas?

Pandas is another Python package which is very popular for data analysis. The key feature of pandas is the `dataframe`. Here we will discuss dataframes and some basic analysis.

NumPy is useful when you are working with data that is all numeric. Pandas, however, is capable of handling data of lots of different types. It is designed to make working with “relational” or “labeled” data easy and intuitive. Central to the `pandas` package are the special data structures called pandas Series and DataFrames. Pandas dataframes are 2 dimensional and tabular, and is particularly suited to data which is heterogenous and in columns, like an Excel spreadsheet. In fact, there are even functions which allow you to read data directly from excel spreadsheets (more on this later).

Pandas is built to closely work with NumPy. Many functions which work on NumPy arrays will also work on Pandas DataFrames.

First we need to load `pandas` it is often abbreviated as `pd`.

In [46]:
import pandas as pd


For this section, we will be working with a data set that contains information about the elements in the periodic table.The data is a csv (comma separated value) file from PubChem. 

Once you have the file downloaded and saved in your directory, we will load it into pandas. This file is a csv (comma separated value) file, so we will load it using the pd.read_csv command.